// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpN_Cg1vok9Oe8-61PwgDcuKavswOyh70',
    appId: '1:540748163224:web:df25499968b4917680c8ed',
    messagingSenderId: '540748163224',
    projectId: 'nurdar-login02',
    authDomain: 'nurdar-login02.firebaseapp.com',
    storageBucket: 'nurdar-login02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWS-hZTQGGd2BKIoE-IqqVxf5cZfiQUnk',
    appId: '1:540748163224:android:6d6b60c1a44860f780c8ed',
    messagingSenderId: '540748163224',
    projectId: 'nurdar-login02',
    storageBucket: 'nurdar-login02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZ9BZ_-G9jTtAAgoS1IJNU0EM_Lmlhw0',
    appId: '1:540748163224:ios:58dcf548dfcc7e8d80c8ed',
    messagingSenderId: '540748163224',
    projectId: 'nurdar-login02',
    storageBucket: 'nurdar-login02.appspot.com',
    iosClientId: '540748163224-d9mdph37f3lusvroi9sbhadlrcnepnnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.login02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjZ9BZ_-G9jTtAAgoS1IJNU0EM_Lmlhw0',
    appId: '1:540748163224:ios:58dcf548dfcc7e8d80c8ed',
    messagingSenderId: '540748163224',
    projectId: 'nurdar-login02',
    storageBucket: 'nurdar-login02.appspot.com',
    iosClientId: '540748163224-d9mdph37f3lusvroi9sbhadlrcnepnnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.login02',
  );
}
